on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
name: Main Workflow
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/ru/r2cloud/
          ~/.sonar/cache
          ~/.rvm/
        key: ${{ runner.os }}-maven
        restore-keys: |
          ${{ runner.os }}-maven-
      
    - uses: actions/setup-java@v4
      with:
        distribution: 'liberica'
        java-version: '17'

    - name: SonarCloud Scan
      run: mvn clean verify sonar:sonar -Pcoverage -Dsonar.scm.disabled=true -Dsonar.projectKey=dernasherbrezon_apt-man -Dsonar.organization=dernasherbrezon-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.language=java
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
